spring.application.name=email-notification
server.port=8081

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=email-notification-group
spring.kafka.consumer.concurrency=1

notification.kafka.topics.email=email-notification.v1

# user service
users-service.host=http://localhost:8084

# auth service
auth-service.host=http://localhost:8000

# oauth client credentials
oauth.client.id=newClient
oauth.client.secret=newClientSecret
