
volumes:
  keycloak-pg-data:
    name: keycloak-pg-data
    driver: local
  keycloak-pg-preinitdb:
    name: keycloak-pg-preinitdb
    driver: local
  keycloak-pg-initdb:
    name: keycloak-pg-initdb
    driver: local

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  keycloak-x-pg:
    container_name: ws-keycloak-x-pg
    image: docker.io/postgres:${KEYCLOAK_POSTGRES_VERSION}
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DATABASE}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - keycloak-pg-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KEYCLOAK_POSTGRES_USER} -d ${KEYCLOAK_POSTGRES_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  keycloak-x:
    container_name: ws-keycloak-x
    image: docker.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    command: [ "start-dev", "--import-realm", "--verbose" ]
    restart: unless-stopped
    ports:
      - 8000:8080
      - 9000:9000
    healthcheck:
      test: [ "CMD-SHELL", "timeout 5s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1" ]
      interval: 30s
      retries: 15
      start_period: 20s
      timeout: 3s
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB_URL: jdbc:postgresql://ws-keycloak-x-pg:5432/${KEYCLOAK_POSTGRES_DATABASE}
      KC_DB: postgres
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HOSTNAME_PORT: 8080
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_MANAGEMENT_PORT: 9000
    volumes:
      - ./keycloak/import/dev-realm:/opt/keycloak/data/import
    depends_on:
      keycloak-x-pg:
        condition: service_healthy
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "email-notification.v1:1:1,sms-notification.v1:1:1,push-notification.v1:1:1"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
