spring.application.name=sms-notification
server.port=8082

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=sms-notification-group
spring.kafka.consumer.concurrency=1

notification.kafka.topics.sms=sms-notification.v1

# user service
users-service.host=http://localhost:8084

# oauth client credentials
oauth.client.id=newClient
oauth.client.secret=newClientSecret

